### ISSUE TITLE
Add support for loops and if statements

### ISSUE THREAD

**Issue by JabirC** [hunter-classes/fall-2019-136-lab-07-JabirC#1]
It is imperative that the program support for loops and if statements in order to be used for large scale projects.

**Comment by gracereyn** [comment]
Do you mean loops and if statements in the input, or do you want the indent function to include a loop?

**Comment by JabirC** [comment]
in the lab it says:

No support for loops and if statements that don’t have curly braces. For example,
if (c == 'A')
    s = s + c;
will be incorrectly indented as

if (c == 'A')
s = s + c;

so, I wanted the program to correctly indent loops and if statements

**Comment by gracereyn** [comment]
I cant seem to close the issue, but the fix is on my [dev branch.](https://github.com/gracereyn/fall-2019-136-lab-07-JabirC/tree/dev)
